### ISSUE TITLE
Test failure with dev version of haven

### ISSUE THREAD

**Issue by hadley** [btskinner/crosswalkr#1]
```
   > test_check("crosswalkr")
    1. Failure: Failed to assign proper values (@test-encodefrom.R#67) 
    haven::zap_labels(vec) not equal to `act_vals`.
    Attributes: < Modes: list, NULL >
    Attributes: < Lengths: 2, 0 >
    Attributes: < names for target but not for current >
    Attributes: < current is not list-like >
    target is labelled, current is character
```

I'm not sure exactly what is causing this, but it's probably related to the changes to the [labelled class](https://github.com/tidyverse/haven/blob/master/NEWS.md#breaking-changes).

Could you please take a look? I'm planning on submitting haven 2.0 to CRAN on [November 7](https://github.com/tidyverse/haven/issues/399)

**Comment by btskinner** [comment]
Can you try the newest release (v0.2.2) version? It passes checks on my machine and Travis. I'd updated to accommodate the haven changes, but hadn't uploaded to CRAN yet.

**Comment by hadley** [comment]
Ah if the dev version is ok, there's nothing else needed here.
