### ISSUE TITLE
Bug in renamefrom() resulting in an error with labelled version 2.1.0

### ISSUE THREAD

**Issue by larmarange** [btskinner/crosswalkr#2]
Dear @btskinner 

Labelled version 2.1.0 will be released soon. In this new version, additional checking have been added to `var_label()`. The examples provided with `renamefrom()` with now produce an error.

It seems that the problem is https://github.com/btskinner/crosswalkr/blob/56c5c2fd4cbbaff3e04235c72f9228d6b9802501/R/renamefrom.R#L170

When exploring the problem with the debugger, it appeared that the value of `null_label_list` was 

```
$<NA>
NULL
```

Best regards

**Comment by btskinner** [comment]
Thanks for the heads up. I believe the problem is fixed with release [v0.2.3](
https://github.com/btskinner/crosswalkr/tree/v0.2.3).

**Comment by larmarange** [comment]
perfect
