### ISSUE TITLE
Drop of columns with upper-case names

### ISSUE THREAD

**Issue by ekatef** [btskinner/crosswalkr#3]
Dear @btskinner, first of all, thank you so much for the package! 

There is a question relating to the `case_ignore` and `drop_extra` arguments. It seems that if both of them are `TRUE`, it leads to an undeliberate drop is the upper-case names of the `.data` data frame, as reported in [this question](https://stackoverflow.com/q/54937388/8465924). 

As I can see, that is connected with the following `renamefrom_( )` code chunk

```
names_ <- names(.data)
if (case_ignore) {
    names_ <- tolower(names_)
}
if (drop_extra) {
    .data <- .data[names_ %in% cw[[raw]]]
    names_ <- names(.data)
    if (case_ignore) {
        names_ <- tolower(names_)
    }
}
```
So, if `case_ignore == TRUE`, we first change all the column names to the lower case. Then if `drop_extra == TRUE` we compare these lower-cased names with the raw ones, which leads to the drop of the columns which names we have just modified ourselves. 

Probably, it makes sense to add an additional case_ignore -check into the drop_extra-statement? Something like this:

```
if (drop_extra) {
    if (case_ignore) {
        .data <- .data[names_ %in% tolower(cw[[raw]])]
    } else {
        .data <- .data[names_ %in% cw[[raw]]]
    }
    names_ <- names(.data)
}  
```  
Best regards

**Comment by btskinner** [comment]
Thanks for the catch. I've made a slightly different change than suggested in order to reduce the need for further `if` clauses downstream. I've added some new tests and everything seems to be in order now.

**Comment by ekatef** [comment]
Many thanks for the prompt fix!
